# Generated by Django 3.2.13 on 2022-11-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.CharField(choices=[('한식', '한식'), ('분식', '분식'), ('중식', '중식'), ('일식', '일식'), ('양식', '양식'), ('아시안', '아시안'), ('카페/디저트', '카페/디저트'), ('기타', None)], default='선택', max_length=10),
        ),
    ]
