# Generated by Django 3.2.13 on 2022-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('Prof_title', models.TextField()),
                ('major', models.TextField()),
                ('number', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
