# Generated by Django 3.2.13 on 2022-11-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
