# Generated by Django 3.2.13 on 2022-11-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='grades',
        ),
    ]
