# Generated by Django 3.2.13 on 2022-11-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_review_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
