# Generated by Django 3.2.13 on 2022-11-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='position',
            field=models.CharField(choices=[('선택', None), ('분식', '분식'), ('치킨', '치킨'), ('피자', '피자')], default='선택', max_length=10),
        ),
    ]
