# Generated by Django 3.2.13 on 2022-11-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221103_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('선택', None), ('분식', '분식'), ('치킨', '치킨'), ('피자', '피자')], default='선택', max_length=10),
        ),
    ]
