# Generated by Django 3.2.13 on 2022-11-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('먹보', None), ('한식', '한식'), ('분식', '분식'), ('중식', '중식'), ('일식', '일식'), ('양식', '양식'), ('아시안', '아시안'), ('카페/디저트', '카페/디저트')], default='선택', max_length=10),
        ),
    ]
