# Generated by Django 3.2.13 on 2022-11-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
