# Generated by Django 3.2.13 on 2022-11-07 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Freecomment',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='Freereview',
        ),
    ]
