# Generated by Django 3.2.13 on 2022-11-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
    ]
